version: 2

updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:40"
    cooldown:
      default-days: 5
    commit-message:
      prefix: "build(dbot):"
    open-pull-requests-limit: 3
    directory: "/"
    labels:
      - "dbot"
      - "javascript"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions

  - package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
      time: "03:00"
    commit-message:
      prefix: "chore(dbot):"
    open-pull-requests-limit: 10
    directory: "/"
    labels:
      - "dbot"
      - "dependencies - github actions"
