pool:
  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    node_8:
      node_version: 8.x
    node_10:
      node_version: 10.x

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

  - checkout: self
    clean: true
    fetchDepth: 0

  - script: git checkout $(System.PullRequest.SourceBranch) && yarn commitlint --from=$(System.PullRequest.TargetBranch)
    displayName: 'commitlint'

  - checkout: self
    clean: true

  - script: yarn && ./scripts/ci/test.sh
    displayName: 'test'
