pool:
  vmImage: 'ubuntu-16.04'
strategy:
  matrix:
    node_8_x:
      node_version: 8.x
    node_9_x:
      node_version: 9.x

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: $(node_version)

- script: ./scripts/ci/test.sh
  displayName: 'test'
