pool:
  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    node_8_x:
      node_version: 8.x
    node_10_x:
      node_version: 10.x

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: $(node_version)

- checkout: self
  clean: true
  fetchDepth: 0

- script: yarn && ./scripts/ci/test.sh
  env:
    TARGET_BRANCH: $(System.PullRequest.TargetBranch)
  displayName: 'test'
