name: CI
on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:
    branches:
      - main

env:
  CI: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Commitlint

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Commitlint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: wagoid/commitlint-github-action@v6

  word-blacklist:
    runs-on: ubuntu-latest
    name: Word Blacklist

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Word Blacklist
        env:
          BLACKLIST: ${{ secrets.BLACKLIST }}
        run: ./scripts/word-blacklist.sh

  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version-file: package.json

      - name: Cache Puppeteer browsers
        uses: actions/cache@v5
        with:
          path: ~/.cache/puppeteer
          key: ${{ runner.os }}-puppeteer-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-puppeteer-

      - name: Install
        run: npm run ci

      - name: Unit Tests
        run: npm run test:unit --no-cache --maxWorkers 2 --no-verbose

      - name: Publish Coverage Report
        uses: zgosalvez/github-actions-report-lcov@v7
        with:
          coverage-files: coverage/lcov.info
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true

      - name: Integration Tests
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        run: npm run test:integration --no-cache --maxWorkers 2


  compile-lint-verify:
    runs-on: ubuntu-latest
    name: Compile, Lint & Verify

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version-file: package.json

      - name: Install
        run: npm run ci

      - name: Compile CJS
        run: npm run compile:cjs

      - name: Compile ESM
        run: npm run compile:esm

      - name: Lint
        run: npm run lint

      - name: Verify
        run: npm run verify

  size-limit:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Size Limit

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version-file: package.json

      - name: Size Limit
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: compile
