name: CI
on:
  push:
    branches:
      - master
    tags-ignore:
      - v*
  pull_request:
    branches:
      - master

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Commitlint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: wagoid/commitlint-github-action@v3

  word-blacklist:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Word Blacklist
        env:
          BLACKLIST: ${{ secrets.BLACKLIST }}
        run: ./scripts/word-blacklist.sh

  test:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install
        run: yarn install

      - name: Unit Tests
        run: yarn test:unit --no-cache --maxWorkers 2 --no-verbose

      - name: Integration Tests
        run:
          find packages/demos -iname '*test.ts*' | xargs -n 2 yarn jest --silent
          --no-cache --no-verbose --no-coverage --maxWorkers 2 --forceExit

  compile-lint-verify:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install
        run: yarn install

      - name: Compile
        run: yarn compile

      - name: Lint
        run: yarn lint

      - name: Verify
        run: yarn verify

      - name: Size Limit
        run: yarn size-limit
