name: CI
on:
  push:
    branches:
      - master
    tags-ignore:
      - v*
  pull_request:
    branches:
      - master

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Commitlint

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Commitlint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: wagoid/commitlint-github-action@v3

  word-blacklist:
    runs-on: ubuntu-latest
    env:
      CI: true
    name: Word Blacklist

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Word Blacklist
        env:
          BLACKLIST: ${{ secrets.BLACKLIST }}
        run: ./scripts/word-blacklist.sh

  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node: ['18', '20']
    name: Test (Node ${{ matrix.node }})

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: yarn install

      - name: Unit Tests
        run: yarn test:unit --no-cache --maxWorkers 2 --no-verbose

      - name: Integration Tests
        run: yarn test:integration --no-cache --maxWorkers 2

  compile-lint-verify:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node: ['18', '20']
    name: Compile, Lint & Verify (Node ${{ matrix.node }})

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: yarn install

      - name: Compile CJS
        run: yarn compile

      - name: Compile ESM
        run: yarn compile:esm

      - name: Lint
        run: yarn lint

      - name: Verify
        run: yarn verify

      - name: Size Limit
        run: yarn size-limit
