name: Cleanup Stacks
on:
  schedule:
    - cron: '0 4 * * MON-FRI'

jobs:
  cleanup-stacks:
    runs-on: ubuntu-latest
    env:
      CI: true
    name: Cleanup Stacks

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: Install
        run: yarn install

      - name: Cleanup
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_HOSTED_ZONE_NAME: ${{ secrets.AWS_HOSTED_ZONE_NAME }}
        run: yarn aws-simple purge --min-age 5 --yes
