name: Commands
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  deploy:
    if: |
      github.event.issue.pull_request && github.event.comment.body == '/deploy'
    runs-on: ubuntu-latest
    env:
      CI: true
    name: Deploy PR

    steps:
      - name: Check user permission
        id: check
        uses: scherermichael-oss/action-has-permission@1.0.6
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add comment reaction
        uses: actions/github-script@v9
        with:
          github-token: ${{ github.token }}
          result-encoding: string
          script: |
            const {comment, repository} = context.payload;

            await github.rest.reactions.createForIssueComment({
              owner: repository.owner.login,
              repo: repository.name,
              comment_id: comment.id,
              content: '${{ steps.check.outputs.has-permission }}' ? '+1' : '-1'
            });

      - name: Abort if prohibited
        if: '! steps.check.outputs.has-permission'
        run: |
          echo "Permissions are insufficient."
          exit 1

      - name: Get PR Head SHA
        uses: actions/github-script@v9
        id: gitSha
        with:
          github-token: ${{ github.token }}
          result-encoding: string
          script: |
            const {issue, repository} = context.payload;

            const pull_request = await github.rest.pulls.get({
              owner: repository.owner.login,
              repo: repository.name,
              pull_number: issue.number
            });

            const {sha} = pull_request.data.head;
            core.setOutput('short', sha.slice(0, 8));
            return sha;

      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ steps.gitSha.outputs.result }}

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version-file: package.json
          registry-url: https://registry.npmjs.org
          scope: '@feature-hub'

      - name: Install
        run: npm run ci

      - name: Generate Website
        run: npm run generate:website

      - name: Compile
        run: npm run compile:cjs

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_HOSTED_ZONE_NAME: ${{ secrets.AWS_HOSTED_ZONE_NAME }}
          AWS_ALIAS_RECORD_NAME: ${{ steps.gitSha.outputs.short }}
        run: npm run deploy -- --require-approval never

      - name: Add PR Comment
        uses: actions/github-script@v9
        with:
          github-token: ${{ github.token }}
          script: |
            const {issue, repository} = context.payload;

            github.rest.issues.createComment({
              owner: repository.owner.login,
              repo: repository.name,
              issue_number: issue.number,
              body: 'Deployed to https://${{ steps.gitSha.outputs.short }}.${{ secrets.AWS_HOSTED_ZONE_NAME }}'
            });
