name: Deploy Master
on:
  push:
    branches:
      - master

jobs:
  deploy-master:
    runs-on: ubuntu-latest
    env:
      CI: true
    name: Deploy master

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: Install
        run: yarn install

      - name: Build Website
        run: yarn lerna exec --scope @feature-hub/website 'docusaurus-build'

      - name: Compile
        run: yarn compile

      - name: Generate API Docs
        run: yarn run generate:api-docs

      - name: Build TodoMVC
        run: yarn lerna run --scope @feature-hub/demos build:todomvc

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_HOSTED_ZONE_NAME: ${{ secrets.AWS_HOSTED_ZONE_NAME }}
        run: |
          yarn deploy --require-approval never
