name: Deploy Main
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    env:
      CI: true
    name: Deploy main

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version-file: package.json

      - name: Install
        run: npm run ci

      - name: Generate Website
        run: npm run generate:website

      - name: Compile
        run: npm run compile:cjs

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_HOSTED_ZONE_NAME: ${{ secrets.AWS_HOSTED_ZONE_NAME }}
        run: |
          npm run deploy -- --require-approval never
