name: Deploy Pages
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      CI: true
    name: Generate pages

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version-file: package.json

      - name: Install
        run: npm run ci

      - name: Generate Website
        run: npm run generate:website

      - name: Compile
        run: npm run compile:cjs

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/website/build/feature-hub

  deploy:
    name: Deploy to GitHub Pages
    needs: generate

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
