name: Release
on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: Create and publish prerelease versions
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: main
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version-file: package.json

      - name: Install
        run: npm run ci

      - name: Compile
        run: npm run compile

      - name: Create Version
        run: |
          git config --global user.email "s2-feature-hub@accenture.com"
          git config --global user.name "Feature Hub CI"
          if [ "${{ inputs.prerelease }}" = "true" ]; then
            npx lerna version prerelease --conventional-commits --conventional-prerelease --preid alpha --no-push --yes
          else
            npx lerna version --conventional-commits --no-push --yes
          fi

      - name: Publish Version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}"
          if [ "${{ inputs.prerelease }}" = "true" ]; then
            npx lerna publish from-git --yes --no-verify-access --dist-tag next
          else
            npx lerna publish from-git --yes --no-verify-access
          fi

      - name: Push Changes
        run: git push --follow-tags
